export interface Book {
  id: number;
  name: string;
  author: string;
  price: number;
  actualPrice: number;
  discount: number;
  isbn: string;
  edition: string;
  image: string;
  description: string;
  category: string;
  program: 'BSc' | 'GNM' | 'Post-Basic';
  semester?: number;
  rating: number;
  reviews: number;
  inStock: boolean;
}

export const booksData: Book[] = [
  {
    id: 1,
    name: 'Advanced Nursing Care',
    author: 'Dr. Sarah Johnson',
    price: 450,
    actualPrice: 599,
    discount: 25,
    isbn: '978-0-12-345678-1',
    edition: '3rd Edition',
    image: 'https://images.unsplash.com/photo-1507842217343-583f20270319?w=500&h=700&fit=crop',
    description: 'Comprehensive guide to advanced nursing practices and clinical care methodologies for healthcare professionals.',
    category: 'Nursing',
    program: 'BSc',
    semester: 1,
    rating: 4.5,
    reviews: 234,
    inStock: true,
  },
  {
    id: 2,
    name: 'Clinical Pharmacology Essentials',
    author: 'Prof. Michael Chen',
    price: 550,
    actualPrice: 699,
    discount: 21,
    isbn: '978-0-12-345678-2',
    edition: '2nd Edition',
    image: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=500&h=700&fit=crop',
    description: 'Essential guide to understanding drug interactions and clinical pharmacology in modern healthcare settings.',
    category: 'Pharmacology',
    program: 'BSc',
    semester: 2,
    rating: 4.7,
    reviews: 567,
    inStock: true,
  },
  {
    id: 3,
    name: 'Medical Diagnosis & Treatment',
    author: 'Dr. Emily Roberts',
    price: 625,
    actualPrice: 799,
    discount: 22,
    isbn: '978-0-12-345678-3',
    edition: '5th Edition',
    image: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=500&h=700&fit=crop',
    description: 'Definitive resource for medical diagnosis, differential diagnosis, and evidence-based treatment approaches.',
    category: 'Medicine',
    program: 'GNM',
    semester: 1,
    rating: 4.8,
    reviews: 892,
    inStock: true,
  },
  {
    id: 4,
    name: 'Pediatric Care Guide',
    author: 'Dr. James Wilson',
    price: 495,
    actualPrice: 649,
    discount: 24,
    isbn: '978-0-12-345678-4',
    edition: '4th Edition',
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=500&h=700&fit=crop',
    description: 'Complete guide to pediatric assessment, care planning, and treatment for children of all ages.',
    category: 'Pediatrics',
    program: 'GNM',
    semester: 2,
    rating: 4.6,
    reviews: 345,
    inStock: true,
  },
  {
    id: 5,
    name: 'Surgery Fundamentals',
    author: 'Dr. Richard Anderson',
    price: 750,
    actualPrice: 999,
    discount: 25,
    isbn: '978-0-12-345678-5',
    edition: '1st Edition',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=500&h=700&fit=crop',
    description: 'Comprehensive surgical reference covering fundamental techniques, procedures, and operative management.',
    category: 'Surgery',
    program: 'Post-Basic',
    rating: 4.9,
    reviews: 456,
    inStock: true,
  },
  {
    id: 6,
    name: 'Pathology & Laboratory Medicine',
    author: 'Dr. Patricia Brown',
    price: 580,
    actualPrice: 749,
    discount: 23,
    isbn: '978-0-12-345678-6',
    edition: '3rd Edition',
    image: 'https://images.unsplash.com/photo-1576091160550-112ba8d25d1d?w=500&h=700&fit=crop',
    description: 'Essential guide to pathological diagnosis, laboratory testing, and interpretation of medical results.',
    category: 'Pathology',
    program: 'BSc',
    semester: 3,
    rating: 4.4,
    reviews: 289,
    inStock: true,
  },
  {
    id: 7,
    name: 'Cardiology Clinical Practice',
    author: 'Dr. David Kumar',
    price: 695,
    actualPrice: 899,
    discount: 23,
    isbn: '978-0-12-345678-7',
    edition: '2nd Edition',
    image: 'https://images.unsplash.com/photo-1576091160550-112ba8d25d1d?w=500&h=700&fit=crop',
    description: 'Advanced cardiology reference covering cardiac diseases, diagnostics, and therapeutic interventions.',
    category: 'Cardiology',
    program: 'Post-Basic',
    rating: 4.7,
    reviews: 678,
    inStock: true,
  },
  {
    id: 8,
    name: 'Oncology & Cancer Care',
    author: 'Dr. Lisa Martinez',
    price: 820,
    actualPrice: 1099,
    discount: 25,
    isbn: '978-0-12-345678-8',
    edition: '1st Edition',
    image: 'https://images.unsplash.com/photo-1576091160550-112ba8d25d1d?w=500&h=700&fit=crop',
    description: 'Comprehensive oncology guide including cancer diagnosis, staging, treatment, and supportive care.',
    category: 'Oncology',
    program: 'Post-Basic',
    rating: 4.8,
    reviews: 523,
    inStock: true,
  },
  {
    id: 9,
    name: 'Neurology Reference Manual',
    author: 'Dr. Robert Taylor',
    price: 615,
    actualPrice: 799,
    discount: 23,
    isbn: '978-0-12-345678-9',
    edition: '2nd Edition',
    image: 'https://images.unsplash.com/photo-1576091160550-112ba8d25d1d?w=500&h=700&fit=crop',
    description: 'Definitive neurological reference covering disorders, investigations, and management strategies.',
    category: 'Neurology',
    program: 'GNM',
    semester: 3,
    rating: 4.6,
    reviews: 412,
    inStock: false,
  },
  {
    id: 10,
    name: 'Emergency Medicine Handbook',
    author: 'Dr. Amanda Lee',
    price: 540,
    actualPrice: 699,
    discount: 23,
    isbn: '978-0-12-345678-10',
    edition: '3rd Edition',
    image: 'https://images.unsplash.com/photo-1576091160550-112ba8d25d1d?w=500&h=700&fit=crop',
    description: 'Quick reference guide for emergency management, acute care protocols, and critical interventions.',
    category: 'Emergency Medicine',
    program: 'BSc',
    semester: 4,
    rating: 4.5,
    reviews: 634,
    inStock: true,
  },
  {
    id: 11,
    name: 'Infectious Diseases Guide',
    author: 'Dr. Christopher Lee',
    price: 495,
    actualPrice: 649,
    discount: 24,
    isbn: '978-0-12-345678-11',
    edition: '4th Edition',
    image: 'https://images.unsplash.com/photo-1576091160550-112ba8d25d1d?w=500&h=700&fit=crop',
    description: 'Comprehensive guide to infectious disease diagnosis, microbiology, and evidence-based treatment.',
    category: 'Infectious Diseases',
    program: 'GNM',
    rating: 4.5,
    reviews: 356,
    inStock: true,
  },
  {
    id: 12,
    name: 'Mental Health & Psychiatry',
    author: 'Dr. Jennifer White',
    price: 480,
    actualPrice: 599,
    discount: 20,
    isbn: '978-0-12-345678-12',
    edition: '3rd Edition',
    image: 'https://images.unsplash.com/photo-1576091160550-112ba8d25d1d?w=500&h=700&fit=crop',
    description: 'Psychiatric reference covering mental disorders, psychopharmacology, and therapeutic approaches.',
    category: 'Psychiatry',
    program: 'Post-Basic',
    rating: 4.4,
    reviews: 298,
    inStock: true,
  },
];

export const categories = [
  'All',
  'Nursing',
  'Pharmacology',
  'Medicine',
  'Pediatrics',
  'Surgery',
  'Pathology',
  'Cardiology',
  'Oncology',
  'Neurology',
  'Emergency Medicine',
  'Infectious Diseases',
  'Psychiatry',
];

export const priceRanges = [
  { label: 'All Prices', min: 0, max: Infinity },
  { label: '₹0 - ₹500', min: 0, max: 500 },
  { label: '₹500 - ₹750', min: 500, max: 750 },
  { label: '₹750 - ₹1000', min: 750, max: 1000 },
  { label: '₹1000+', min: 1000, max: Infinity },
];

export const sortOptions = [
  { label: 'Relevance', value: 'relevance' },
  { label: 'Price: Low to High', value: 'price-low' },
  { label: 'Price: High to Low', value: 'price-high' },
  { label: 'Newest', value: 'newest' },
  { label: 'Highest Rated', value: 'rating' },
  { label: 'Most Reviewed', value: 'reviews' },
];
